data_load:
  dataset_csv: "data/houses.csv"
featurize:
  features_path: "data/final.csv"
data_split:
  test_size: 0.2
  trainset_path: "data/train_houses.csv"
  testset_path: "data/test_houses.csv"
train:
  cv: 4
  model_type: "ridge"
  alpha: [0.0001, 0.001, 0.01, 0.05, 0.5]
  max_iter: [800,900,1000,1100]
  tol: [0.0001, 0.001, 0.0004]
  model_path: "models/houses.joblib"
  power_path: "models/power.joblib"
test:
  model_path: "models/houses.joblib"
  power_path: "models/power.joblib"
  testset_path: "data/test_houses.csv"
  
